name: Documentation Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-docs:
    name: Build HTML documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade sphinx
          python -m pip install .
          python -m pip install -r docs/requirements.txt

      - name: Build Sphinx documentation
        working-directory: docs
        run: sphinx-build -T -W --keep-going -b html -d _build/doctrees -D language=en . _build/html
